# Я сюда сам внес незначительные изменения, связанные с дизайном
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setGeometry(0, 0, 1920, 1010)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_sections = QtWidgets.QTabWidget(self.centralwidget)
        self.main_sections.setGeometry(QtCore.QRect(0, 0, 1921, 991))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_sections.sizePolicy().hasHeightForWidth())
        self.main_sections.setSizePolicy(sizePolicy)
        self.main_sections.setObjectName("main_sections")
        self.Teachers = QtWidgets.QWidget()
        self.Teachers.setObjectName("Teachers")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Teachers)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1911, 891))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.main_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.main_titles = QtWidgets.QHBoxLayout()
        self.main_titles.setObjectName("main_titles")
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.main_titles.addItem(spacerItem)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.main_titles.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.main_titles.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.main_titles.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.main_titles.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.main_titles.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.main_titles.addWidget(self.label_6)
        self.main_layout.addLayout(self.main_titles, 0, 0, 1, 1)
        self.timetable = QtWidgets.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timetable.sizePolicy().hasHeightForWidth())
        self.timetable.setSizePolicy(sizePolicy)
        self.timetable.setObjectName("timetable")
        self.timetable.setColumnCount(0)
        self.timetable.setRowCount(0)
        self.timetable.horizontalHeader().setVisible(True)
        self.timetable.horizontalHeader().setCascadingSectionResizes(False)
        self.timetable.horizontalHeader().setDefaultSectionSize(36)
        self.timetable.horizontalHeader().setHighlightSections(True)
        self.timetable.horizontalHeader().setMinimumSectionSize(36)
        self.timetable.horizontalHeader().setSortIndicatorShown(False)
        self.timetable.horizontalHeader().setStretchLastSection(False)
        self.timetable.verticalHeader().setCascadingSectionResizes(True)
        self.timetable.verticalHeader().setSortIndicatorShown(False)
        self.timetable.verticalHeader().setStretchLastSection(False)
        self.timetable.verticalHeader().setDefaultSectionSize(25)
        self.main_layout.addWidget(self.timetable, 1, 0, 1, 1)
        self.school_forms = QtWidgets.QHBoxLayout()
        self.school_forms.setObjectName("school_forms")
        self.main_layout.addLayout(self.school_forms, 2, 0, 1, 1)
        self.main_sections.addTab(self.Teachers, "")
        self.Forms = QtWidgets.QWidget()
        self.Forms.setObjectName("Forms")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Forms)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1911, 891))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_titles_2 = QtWidgets.QHBoxLayout()
        self.main_titles_2.setObjectName("main_titles_2")
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.main_titles_2.addItem(spacerItem1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.main_titles_2.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.main_titles_2.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.main_titles_2.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.main_titles_2.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.main_titles_2.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.main_titles_2.addWidget(self.label_26)
        self.gridLayout_2.addLayout(self.main_titles_2, 0, 0, 1, 1)
        self.Lessons = QtWidgets.QHBoxLayout()
        self.Lessons.setObjectName("Lessons")
        self.gridLayout_2.addLayout(self.Lessons, 2, 0, 1, 1)
        self.timetable_2 = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.timetable_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.timetable_2.setObjectName("timetable_2")
        self.timetable_2.setColumnCount(0)
        self.timetable_2.setRowCount(0)
        self.timetable_2.horizontalHeader().setVisible(True)
        self.timetable_2.horizontalHeader().setCascadingSectionResizes(False)
        self.timetable_2.horizontalHeader().setDefaultSectionSize(36)
        self.timetable_2.horizontalHeader().setMinimumSectionSize(36)
        self.timetable_2.verticalHeader().setCascadingSectionResizes(True)
        self.timetable_2.verticalHeader().setDefaultSectionSize(25)
        self.gridLayout_2.addWidget(self.timetable_2, 1, 0, 1, 1)
        self.main_sections.addTab(self.Forms, "")
        self.Changing_info = QtWidgets.QWidget()
        self.Changing_info.setObjectName("Changing_info")
        self.sections = QtWidgets.QTabWidget(self.Changing_info)
        self.sections.setGeometry(QtCore.QRect(0, 10, 1911, 941))
        self.sections.setObjectName("sections")
        self.teachers_section = QtWidgets.QWidget()
        self.teachers_section.setObjectName("teachers_section")
        self.info_teachers_table = QtWidgets.QTableWidget(self.teachers_section)
        self.info_teachers_table.setGeometry(QtCore.QRect(10, 10, 830, 991))
        self.info_teachers_table.setObjectName("info_teachers_table")
        self.info_teachers_table.setColumnCount(6)
        self.info_teachers_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.info_teachers_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_teachers_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_teachers_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_teachers_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_teachers_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_teachers_table.setHorizontalHeaderItem(5, item)
        self.info_teachers_table.horizontalHeader().setStretchLastSection(True)
        self.info_teachers_table.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.teachers_section)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(940, 70, 271, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.info_labels = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.info_labels.setContentsMargins(0, 0, 0, 0)
        self.info_labels.setObjectName("info_labels")
        self.info_label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.info_label_1.setObjectName("info_label_1")
        self.info_labels.addWidget(self.info_label_1)
        self.info_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.info_label_2.setObjectName("info_label_2")
        self.info_labels.addWidget(self.info_label_2)
        self.info_label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.info_label_3.setObjectName("info_label_3")
        self.info_labels.addWidget(self.info_label_3)
        self.sections.addTab(self.teachers_section, "")
        self.classrooms_section = QtWidgets.QWidget()
        self.classrooms_section.setObjectName("classrooms_section")
        self.info_classrooms_table = QtWidgets.QTableWidget(self.classrooms_section)
        self.info_classrooms_table.setGeometry(QtCore.QRect(10, 10, 325, 991))
        self.info_classrooms_table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.info_classrooms_table.verticalHeader().setDefaultSectionSize(25)
        self.info_classrooms_table.setObjectName("info_classrooms_table")
        self.info_classrooms_table.setColumnCount(3)
        self.info_classrooms_table.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.info_classrooms_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_classrooms_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_classrooms_table.setHorizontalHeaderItem(2, item)
        self.info_classrooms_table.horizontalHeader().setCascadingSectionResizes(False)
        self.info_classrooms_table.horizontalHeader().setHighlightSections(True)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.classrooms_section)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(560, 20, 281, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.info_labels_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.info_labels_2.setContentsMargins(0, 0, 0, 0)
        self.info_labels_2.setObjectName("info_labels_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.info_labels_2.addWidget(self.label)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.info_labels_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.info_labels_2.addWidget(self.label_8)
        self.sections.addTab(self.classrooms_section, "")
        self.forms_section = QtWidgets.QWidget()
        self.forms_section.setObjectName("forms_section")
        self.info_forms_table = QtWidgets.QTableWidget(self.forms_section)
        self.info_forms_table.setGeometry(QtCore.QRect(10, 10, 366, 991))
        self.info_forms_table.setObjectName("info_forms_table")
        self.info_forms_table.setColumnCount(3)
        self.info_forms_table.setRowCount(10)
        self.info_forms_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeToContents)
        self.info_forms_table.verticalHeader().setDefaultSectionSize(25)
        item = QtWidgets.QTableWidgetItem()
        self.info_forms_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_forms_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_forms_table.setHorizontalHeaderItem(2, item)
        self.info_forms_table.horizontalHeader().setCascadingSectionResizes(False)
        self.sections.addTab(self.forms_section, "")
        self.lessons_section = QtWidgets.QWidget()
        self.lessons_section.setObjectName("lessons_section")
        self.info_lessons_table = QtWidgets.QTableWidget(self.lessons_section)
        self.info_lessons_table.setGeometry(QtCore.QRect(10, 10, 225, 227))
        self.info_lessons_table.setObjectName("info_lessons_table")
        self.info_lessons_table.setColumnCount(2)
        self.info_lessons_table.setRowCount(8)
        self.info_lessons_table.verticalHeader().setDefaultSectionSize(25)
        item = QtWidgets.QTableWidgetItem()
        self.info_lessons_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_lessons_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.info_lessons_table.setHorizontalHeaderItem(2, item)
        self.info_lessons_table.horizontalHeader().setStretchLastSection(True)
        self.sections.addTab(self.lessons_section, "")
        self.main_sections.addTab(self.Changing_info, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1936, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.showMessage('Statusbar')
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_sections.setCurrentIndex(0)
        self.sections.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Schedule Helper"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Понедельник</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Вторник</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Среда</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Четверг</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Пятница</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Суббота</span></p></body></html>"))
        self.main_sections.setTabText(self.main_sections.indexOf(self.Teachers), _translate("MainWindow", "Расписание учителей"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Понедельник</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Вторник</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Среда</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Четверг</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Пятница</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Суббота</span></p></body></html>"))
        self.main_sections.setTabText(self.main_sections.indexOf(self.Forms), _translate("MainWindow", "Расписание классов"))
        item = self.info_teachers_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ФИО"))
        item = self.info_teachers_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Предмет"))
        item = self.info_teachers_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Кл-ное рук-во"))
        item = self.info_teachers_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Кабинет"))
        item = self.info_teachers_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Часов в неделю"))
        item = self.info_teachers_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Список классов, в которых учитель ведет уроки"))
        self.info_label_1.setText(_translate("MainWindow", "В Списке классов, где учитель ведет уроки"))
        self.info_label_2.setText(_translate("MainWindow", "через запятую и пробел указать классы"))
        self.info_label_3.setText(_translate("MainWindow", "Например \"5Б, 6А, 6В, 7А\""))
        self.sections.setTabText(self.sections.indexOf(self.teachers_section), _translate("MainWindow", "Учителя"))
        item = self.info_classrooms_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№ кабинета"))
        item = self.info_classrooms_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Предмет"))
        item = self.info_classrooms_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Учитель"))
        self.label.setText(_translate("MainWindow", "Предмет - основной предмет, который"))
        self.label_7.setText(_translate("MainWindow", "преподается в этом кабинете;"))
        self.label_8.setText(_translate("MainWindow", "Учитель - ответственный за данный кабинет"))
        self.sections.setTabText(self.sections.indexOf(self.classrooms_section), _translate("MainWindow", "Кабинеты"))
        item = self.info_forms_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Класс"))
        item = self.info_forms_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Классный руководитель"))
        item = self.info_forms_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Профиль"))
        self.sections.setTabText(self.sections.indexOf(self.forms_section), _translate("MainWindow", "Классы"))
        item = self.info_lessons_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Начало"))
        item = self.info_lessons_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Конец"))
        self.sections.setTabText(self.sections.indexOf(self.lessons_section), _translate("MainWindow", "Уроки"))
        self.main_sections.setTabText(self.main_sections.indexOf(self.Changing_info), _translate("MainWindow", "Изменение основной инфромации"))
